- name: Download python Content & Extract it
  become: yes:
  get_url:
    url: https://github.com/prasanthbangs2016/spoorthy-python/archive/main.zip
    dest: /tmp
    remote_src: yes


- name: Copy python Content
  ansible.builtin.copy:
    src: /tmp/main/
    dest: /home/centos/
    remote_src: yes
