- name: Spoorthy code 
  hosts: all
  tasks:

  - name: Remove Old APP Content
    ansible.builtin.file:
      path: /tmp/main
      state: absent

  - name: Download python Content & Extract it
    ansible.builtin.unarchive:
      src: "https://github.com/prasanthbangs2016/spoorthy-python/archive/main.zip"
      dest: /tmp/main
      remote_src: yes


  - name: Copy python Content
    ansible.builtin.copy:
      src: /tmp/main/
      dest: /home/centos/
      remote_src: yes

  - name: Run python script
    ansible.builtin.command: python3 /home/centos/spoorthy-python-main/uname.py &>/tmp/uname-output.log
